spring:
  data:
    mongodb:
      database: livegoods
      host: 192.168.197.143
      username: lbaci
      password: lbaci
      port: 27017
      authentication-database: admin
  application:
    name: backenduesrloginservice

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tx-lcn:
  client:
    manager-address: 192.168.197.136:8070
