spring:
  application:
    name: fontenduserlogin
server:
  port: 9011

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


tx-lcn:
  client:
    manager-address: 192.168.197.136:8070
