spring:
  application:
    name: userservice
  data:
    mongodb:
      host: 192.168.197.143
      username: lbaci
      password: lbaci
      port: 27017
      authentication-database: amdin
      database: livegoods
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tx-lcn:
  client:
    manager-address: 192.168.197.136:8070
server:
  port: 9098
