spring:
  application:
    name: backendbyrecommenserver
  data:
    mongodb:
      database: livegoods
      host: 192.168.197.143
      username: lbaci
      password: lbaci
      authentication-database: admin

server:
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
