spring:
  application:
    name: portalserver

server:
  port:9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tx-lcn:
  client:
    manager-address: 192.168.197.136:8070

