server:
  port: 9090
spring:
  application:
    name: backendserver
  data:
    mongodb:
      host: 192.168.197.143
      username: lbaci
      password: lbaci
      port: 27017
      authentication-database: admin
      database: livegoods
ureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


