spring:
  data:
    mongodb:
      host: 192.168.197.143
      username: lbaci
      password: lbaci
      authentication-database: admin
      database: livegoods
      port: 27017
  application:
    name: backendvalidatecode
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9020
